let postData = [
  {
    id: 1,
    src: `Post-Images/yellow-rose-nursery.jpg`,
    title: "yellow Rose",
    price: "$25.00",
    season: "spring",
    category:"flower",
    description:"skdmskdmksdskdskd",
    discount:"$15.00",
  },
  {
    id: 2,
    src: `Post-Images/redRose.png`,
    title: "Red Rose",
    price: "$25.00",
    season: "summer",
    category:"flower",
    description:"skdmskdmksdskdskd",
    discount:"$18.90",
  },
  {
    id: 3,
    src: `Post-Images/black rose nursery.jpg`,
    title: "Black Magic Roze",
    price: "$42.00",
    season: "autumn",
    category:"flower",
    description:"skdmskdmksdskdskd",
    discount:"$25.00",
  },

  {
    id: 4,
    src: `Post-Images/pink-rose-nursery.webp`,
    title: "pink rose",
    price: "$34.90",
    season: "winter",
    category:"flower",
    description:"skdmskdmksdskdskd",
    discount:"$22.00",
  },
  {
    id: 5,
    src: `Post-Images/White-Gardenia.avif`,
    title: "White Gardenia",
    price: "$11.50",
    season: "spring",
    category:"tree",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 6,
    src: `Post-Images/Red-rose-nursery.webp`,
    title: "red Rose",
    price: "$18.30",
    season: "summer",
    category:"tree",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 7,
    src: `Post-Images/whitered-rose-nursery.jpg`,
    title: "white red",
    price: "$28.00",
    season: "autumn",
    category:"tree",
    description:"skdmskdmksdskdskd",
    discount:"$15.00",
  },
  {
    id: 8,
    src: `Post-Images/purple-rose-nursery.webp`,
    title: "Purple Rose",
    price: "$21.50",
    season: "winter",
    category:"tree",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 9,
    src: `Post-Images/orange-rose-nuursery.jpg`,
    title: "Orange Rose",
    price: "$39.00",
    season: "spring",
    category:"gift",
    description:"skdmskdmksdskdskd",
    discount:"$27.00",
  },

  {
    id: 10,
    src: `Post-Images/black-rose-nursery.jpg`,
    title: "Black Rose",
    price: "$15.99",
    season: "summer",
    category:"gift",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 11,
    src: `Post-Images/blue-plant.jpg`,
    title: "green Flower",
    price: "$75.00",
    season: "autumn",
    category:"gift",
    description:"skdmskdmksdskdskd",
    discount:"$55.00",
  },
  {
    id: 12,
    src: `Post-Images/Red-rose-nursery.webp`,
    title: "red Rose",
    price: "$18.30",
    season: "winter",
    category:"gift",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 13,
    src: `Post-Images/whitered-rose-nursery.jpg`,
    title: "white red",
    price: "$28.00",
    season: "spring",
    category:"flower",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 14,
    src: `Post-Images/purple-rose-nursery.webp`,
    title: "Purple Rose",
    price: "$21.50",
    season: "summer",
    category:"flower",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 15,
    src: `Post-Images/orange-rose-nuursery.jpg`,
    title: "Orange Rose",
    price: "$39.00",
    season: "autumn",
    category:"flower",
    description:"skdmskdmksdskdskd",
    discount:"",
  },

  {
    id: 16,
    src: `Post-Images/black-rose-nursery.jpg`,
    title: "Black Rose",
    price: "$15.99",
    season: "winter",
    category:"flower",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 17,
    src: `Post-Images/blue-plant.jpg`,
    title: "green Flower",
    price: "$75.00",
    season: "spring",
    category:"tree",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 18,
    src: `Post-Images/Red-rose-nursery.webp`,
    title: "red Rose",
    price: "$18.30",
    season: "summer",
    category:"tree",
    description:"skdmskdmksdskdskd",
    discount:"$10.00",
  },
  {
    id: 19,
    src: `Post-Images/whitered-rose-nursery.jpg`,
    title: "white red",
    price: "$28.00",
    season: "autumn",
    category:"tree",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 20,
    src: `Post-Images/purple-rose-nursery.webp`,
    title: "Purple Rose",
    price: "$21.50",
    season: "winter",
    category:"tree",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 21,
    src: `Post-Images/orange-rose-nuursery.jpg`,
    title: "Orange Rose",
    price: "$39.00",
    season: "spring",
    category:"gift",
    description:"skdmskdmksdskdskd",
    discount:"",
  },

  {
    id: 22,
    src: `Post-Images/black-rose-nursery.jpg`,
    title: "Black Rose",
    price: "$15.99",
    season: "summer",
    category:"gift",
    description:"skdmskdmksdskdskd",
    discount:"$6.99",
  },
  {
    id: 23,
    src: `Post-Images/blue-plant.jpg`,
    title: "green Flower",
    price: "$75.00",
    season: "autumn",
    category:"gift",
    description:"skdmskdmksdskdskd",
    discount:"$60.00",
  },
  {
    id: 24,
    src: `Post-Images/Red-rose-nursery.webp`,
    title: "red Rose",
    price: "$18.30",
    season: "winter",
    category:"gift",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 25,
    src: `Post-Images/whitered-rose-nursery.jpg`,
    title: "white red",
    price: "$28.00",
    season: "fourseasons",
    category:"gift",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 26,
    src: `Post-Images/purple-rose-nursery.webp`,
    title: "Purple Rose",
    price: "$21.50",
    season: "fourseasons",
    category:"flower",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 27,
    src: `Post-Images/orange-rose-nuursery.jpg`,
    title: "Orange Rose",
    price: "$39.00",
    season: "fourseasons",
    category:"flower",
    description:"skdmskdmksdskdskd",
    discount:"",
  },

  {
    id: 28,
    src: `Post-Images/black-rose-nursery.jpg`,
    title: "Black Rose",
    price: "$15.99",
    season: "fourseasons",
    category:"flower",
    description:"skdmskdmksdskdskd",
    discount:"$15.00",
  },
  {
    id: 29,
    src: `Post-Images/blue-plant.jpg`,
    title: "green Flower",
    price: "$75.00",
    season: "fourseasons",
    category:"flower",
    description:"skdmskdmksdskdskd",
    discount:"$35.00",
  },
  {
    id: 30,
    src: `Post-Images/Red-rose-nursery.webp`,
    title: "red Rose",
    price: "$18.30",
    season: "fourseasons",
    category:"tree",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 31,
    src: `Post-Images/whitered-rose-nursery.jpg`,
    title: "white red",
    price: "$28.00",
    season: "fourseasons",
    category:"tree",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 32,
    src: `Post-Images/purple-rose-nursery.webp`,
    title: "Purple Rose",
    price: "$21.50",
    season: "fourseasons",
    category:"tree",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 33,
    src: `Post-Images/orange-rose-nuursery.jpg`,
    title: "Orange Rose",
    price: "$39.00",
    season: "spring",
    category:"tree",
    description:"skdmskdmksdskdskd",
    discount:"",
  },

  {
    id: 34,
    src: `Post-Images/black-rose-nursery.jpg`,
    title: "Black Rose",
    price: "$15.99",
    season: "fourseasons",
    category:"gift",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 35,
    src: `Post-Images/blue-plant.jpg`,
    title: "green Flower",
    price: "$75.00",
    season: "fourseasons",
    category:"gift",
    description:"skdmskdmksdskdskd",
    discount:"$52.70",
  },
  {
    id: 36,
    src: `Post-Images/Red-rose-nursery.webp`,
    title: "red Rose",
    price: "$18.30",
    season: "fourseasons",
    category:"gift",
    description:"skdmskdmksdskdskd",
    discount:"$13.00",
  },
  {
    id: 37,
    src: `Post-Images/whitered-rose-nursery.jpg`,
    title: "white red",
    price: "$28.00",
    season: "winter",
    category:"gift",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 38,
    src: `Post-Images/purple-rose-nursery.webp`,
    title: "Purple Rose",
    price: "$21.50",
    season: "fourseasons",
    category:"flower",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 39,
    src: `Post-Images/orange-rose-nuursery.jpg`,
    title: "Orange Rose",
    price: "$39.00",
    season: "summer",
    category:"flower",
    description:"skdmskdmksdskdskd",
    discount:"$19.50",
  },

  {
    id: 40,
    src: `Post-Images/black-rose-nursery.jpg`,
    title: "Black Rose",
    price: "$15.99",
    season: "autumn",
    category:"flower",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 41,
    src: `Post-Images/blue-plant.jpg`,
    title: "green Flower",
    price: "$75.00",
    season: "spring",
    category:"flower",
    description:"skdmskdmksdskdskd",
    discount:"$50.70",
  },
  {
    id: 42,
    src: `Post-Images/Red-rose-nursery.webp`,
    title: "red Rose",
    price: "$18.30",
    season: "summer",
    category:"tree",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 43,
    src: `Post-Images/whitered-rose-nursery.jpg`,
    title: "white red",
    price: "$28.00",
    season: "autumn",
    category:"tree",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 44,
    src: `Post-Images/purple-rose-nursery.webp`,
    title: "Purple Rose",
    price: "$21.50",
    season: "winter",
    category:"tree",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 45,
    src: `Post-Images/orange-rose-nuursery.jpg`,
    title: "Orange Rose",
    price: "$39.00",
    season: "spring",
    category:"tree",
    description:"skdmskdmksdskdskd",
    discount:"$25.00",
  },
  {
    id: 46,
    src: `Post-Images/black-rose-nursery.jpg`,
    title: "Black Rose",
    price: "$15.99",
    season: "summer",
    category:"gift",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
  {
    id: 47,
    src: `Post-Images/blue-plant.jpg`,
    title: "green Flower",
    price: "$75.00",
    season: "autumn",
    category:"gift",
    description:"skdmskdmksdskdskd",
    discount:"",
  },
];
export default postData;
